apiVersion: v1
kind: Service
metadata:
  name: k8s-mariadb-svc # 주의!
spec:
  selector:
    app: helm-mariadb106
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-fastapi-svc # 주의!
spec:
  selector:
    app: helm-fastapi
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: helm-fanginx-svc
spec:
  selector:
    app: helm-fanginx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80